### PR TITLE
Use coroutines to create modules in parallel

### PR DESCRIPTION
**Pull request by srmurguia**

### CODE REVIEW

**Comment by NikitaKozlov** [comment]
Are you sure that it is faster? You still have only one hard drive, and that is a bottle neck I belive

**Comment by NikitaKozlov** [comment]
Don't understand me wrong, I don't have anything against this PR. Just was curious if you did some measurements. I'll try to do them now.

**Comment by srmurguia** [comment]
I am doing that right now, just for curiosity :p

**Comment by srmurguia** [comment]
You are right, the bottleneck is the drive, but it hides some of the IO latency. On my machine, creating a project with the default settings and 2000 modules takes 19022ms in parallel and 92965ms without coroutines (my machine has a SSD, probably on spinning disk it will not be such an improvement)

**Comment by srmurguia** [comment]
Actually, probably it will a better improvement on spinning disks, I am not sure.

**Comment by NikitaKozlov** [comment]
2000 modules? My mac almost died trying to achieve this without coroutines. With coroutines it did much better job, but still more then 1 min.

**Comment by NikitaKozlov** [comment]
On spinning disks it might be slower, because we are not writing one big stream of bytes, rather a lot of small files. But I'm not sure as well.

**Comment by srmurguia** [comment]
Yes, probably with lots of methods, to make files big enough. I am not near to one to test. 

Also, I tried coroutines on a single thread (using a newSingleThreadContextand) it did not improve, it seems that one single thread cannot use all disk bandwidth. All this conclusions are dependent on hardware anyway, but I think we can assume that it is better to use them.

**Comment by borisf** [comment]
Thanks all merging

**Pull request merged**
