### PR TITLE
Add compose support

### PR DESCRIPTION
**Pull request by picklebento**
## Summary
- The compose variant will be equivalent to data binding. `Modifier.onClick` will be set for `Text()` and `Image()` composeables if we specify actions.

## Test
I added several configs under `configs/compose/` and verify that the generated project can be installed and run without modification.

### CODE REVIEW

**Comment by borisf** [comment]
Thanks @chao2zhang , I will take a deeper look tomorrow

**Comment by borisf** [comment]
@chao2zhang looks great, thanks. Can you kindly add an md file with developer know how (how to use/example/how to modify/add), on how to use etc' thus more developers can understand and resuse the functionality. Happy to help :)

**Comment by picklebento** [comment]
Do you mean to enrich the top-level README.md? Particularly I could add the `composeConfig` there.

Additionally, this PR is not the final PR for me. I am still planning to add a viewBinding option and would like to compare the build speed for plain vs dataBinding vs viewBinding vs compose.

**Comment by borisf** [comment]
Do you mean to enrich the top-level README.md? Particularly I could add the composeConfig there.

Boris - great, let's update the top level README.md, to make sure everyone can understand the functionality


Additionally, this PR is not the final PR for me. I am still planning to add a viewBinding option and would like to compare the build speed for plain vs dataBinding vs viewBinding vs compose.

Boris - this is great, thanks

**Pull request merged**
