### PR TITLE
Fix an NPE issue when there were modules without dependencies

### PR DESCRIPTION
**Pull request by srmurguia**

### CODE REVIEW

**Comment by NikitaKozlov** [comment]
I think after https://github.com/android/android-studio-poet/pull/71, it shouldn't be an issue anymore. I change `allDependencies` a bit and now the way we construct it is the following: `allDependencies = allModuleBlueprints.associate { it -> Pair(it.name, it.dependencies) }`, where `it.dependencies` is empty list by default.

**Comment by srmurguia** [comment]
You are right, it will not be needed.

**Comment by borisf** [comment]
@srmurguia so we don't need this PR, right ?

**Comment by srmurguia** [comment]
I don't think so. I will check in a few hours with the same configuration,but from the code If not expect that we need it. I am closing this PR and create a new one if there are still issues.

**Pull request closed without merging**
