### PR TITLE
Folder processing

### PR DESCRIPTION
**Pull request by borisf**
Added logic to process folders as command line parameters

### CODE REVIEW

**Comment by NikitaKozlov** [comment]
Can you please update readme section with explanations how to run the AS Poet?

**Comment by borisf** [comment]
@NikitaKozlov please take a look

**Comment by NikitaKozlov** [comment]
LGTM, the only small thing that I think worth doing, but it can also be done in another PR: Log amount of files processed and amount of files left. Generating projects takes sometimes a few minutes, so it is useful to know how many configs left. But again, that can also be done in another PR.

**Comment by borisf** [comment]
@NikitaKozlov please take a look, added pretty printing

**Comment by NikitaKozlov** [comment]
Lgtm

**Pull request merged**
