### PR TITLE
Restore dependencies on android modules

### PR DESCRIPTION
**Pull request by NikitaKozlov**
In https://github.com/android/android-studio-poet/pull/68 was accidentally removed usage of Android Module dependencies. Now it is restored and works properly with `AndroidModuleConfig`.
This PR also includes renaming `DependencyConfig` to `FromToDependencyConfig` as one more step towards new input format.

### CODE REVIEW

**Comment by srmurguia** [comment]
I think I have to rebase #74 after this PR, that also restores dependencies and moved name generation to the same place :p

**Comment by borisf** [comment]
@srmurguia @NikitaKozlov what should be the order to merge all PRs, please

**Comment by srmurguia** [comment]
I think it is better if we merge this first, then abandon #74 and create a new one with the other changes (.dot file creation and android module parallelization)

**Comment by NikitaKozlov** [comment]
Ok, then let's merge this one first. If you need help with fixing the other PR after that - let me know.

**Pull request merged**
